### ISSUE TITLE
DryIocServiceHostFactory.SetContainer static state and/or lollipop immutability problem

### ISSUE THREAD

**Issue by igand** [jasper-d/DryIoc.Wcf#3]
Hi,
DryIocServiceHostFactory.SetContainer currently throws, when called more than once and also stores the container in static attribute, which complicates integration tests.
Could either static state or lollipop immutability be removed? 
(While removing static state is way more preffered, lollipop immutability here seems like a good idea)

When integration testing, the method (AutoFixture Customization for me) which configures container often gets called more than once (as not all test can reuse the DI context due some mutable state in it) and possibly with completely different containers. 

Like I have tests, which use 2 set ups - one with DI container with caching things and other without and I test the service behaves still the same, regardless of kind implementations being used.But on the level of WCF service I can't do that now.

**Comment by jasper-d** [comment]
Hi @igand, the short answer is no.
Changing the container instance is an error. Allowing it would cause more harm than good. If you need different containers for your tests you could use separate AppDomains or use self-hosted WCF services and instantiate DryIocServiceHost directly in your test setup. When instantiating DryIocServiceHost directly make sure to register the service with its concrete type and pass it to the constructor, like so:

    container.Register(typeof(SampleService), Reuse.Transient);
    container.Register(typeof(IFoo), typeof(Foo));
    using(var serviceHost = new DryIocServiceHost(container, typeof(SampleService), new Uri("http://localhost:8080/foo"))) {
      //...
    }
